# web 配置
server.port=8080
server.servlet.context-path=/xxl-job-admin

# 调度中心数据库链接
spring.datasource.url=jdbc:mysql://192.168.0.103:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=HelloWorld!@#

# 报警邮箱
spring.mail.host=smtp.qq.com
spring.mail.username=xxx@qq.com
spring.mail.from=xxx@qq.com
spring.mail.password=xxx

# 调度线程池最大线程
xxl.job.triggerpool.fast.max=200
xxl.job.triggerpool.slow.max=100

# 调度中心通讯 token
xxl.job.accessToken=default_token

# 调度中心通讯超时时间
xxl.job.timeout=3

# 调度中心日志表数据保存天数
xxl.job.logretentiondays=30
