version: '2'

services:
  xxl-job-admin:
    build: "./image/"
    container_name: "xxl-job-admin"
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/data/applogs
      - ./conf/application.properties:/application.properties
#      - /etc/localtime:/etc/localtime
#    restart: always
